#!/usr/bin/env python3

import sys
from math import sin, cos, radians

# Define some global variables
world_x1 = 0
world_x2 = 499
world_y1 = 0
world_y2 = 499
width = 0
height = 0

fileName = ""

scaleFactor = 1.0
rotation = 0.0
translateX, translateY = 0, 0

# Simple Point Object
class Vertex():
	def __init__(self,x,y):
		self.x = x
		self.y = y

polygon = [] #Contains a list of vertexs

def processArgs():
	global fileName, scaleFactor, translateX, translateY, rotation, world_y1,world_x1,world_y2, world_x2

	argv = sys.argv
	for i in range(1,len(argv),2):
		if argv[i][0] == '-':
			letter = argv[i][1]
			if letter == "f":
				fileName = argv[i+1] ;
			elif letter == 's':
				scaleFactor = float(argv[i+1]);
			elif letter == 'm':
				translateX = int(argv[i+1]);
			elif letter == 'n':
				translateY = int(argv[i+1]);
			elif letter == 'r':
				rotation = radians(int(argv[i+1]));
			elif letter == 'a':
				world_x1 = int(argv[i+1]);
			elif letter == 'b':
				world_y1 = int(argv[i+1]);
			elif letter == 'c':
				world_x2 = int(argv[i+1]);
			elif letter == 'd':
				world_y2 = int(argv[i+1]);

			
#/////////////////////////////////////
#//READING THE FILE
#/////////////////////////////////////

def readPS():
	global polygon
	line = ""
	f = open(fileName,"r");

	#Ignore all text until %%%BEGIN is reached
	line = f.readline()
	while line != "%%%BEGIN\n":
		line = f.readline()


	#Read till %%%END is reached
	line = f.readline()
	while line != "%%%END\n":
		if line != "stroke\n":
			x, y, word = line.split(" ")
			v = Vertex(int(x),int(y))
			polygon.append(v)

		line = f.readline()

	# while(strncmp(fgets(BUF,

	f.close()

# ////////////////////////////////////////
# //DEBUGGING TOOL FOR THE ARRAY LIST
# ///////////////////////////////////////

def printArray(array):
	print( "ARRAY CHECKER [] ", file=sys.stderr)
	for vertex in polygon:	
		print("%d %d"%( vertex.x, vertex.y), file=sys.stderr)


# ///////////////////////////////////////
# // THE CLIPPING SECTION
# //////////////////////////////////////

TOP = 0
BOTTOM = 1
LEFT = 2
RIGHT = 3

def clipping():

		#Sutherland-Hodgman clipping

		# Look at each case individually, cut off any line that goes further than the point, 
		# add new vertex in the intersept of the line to the boundary

		clipper(TOP)

		clipper(RIGHT)

		clipper(BOTTOM)

		clipper(LEFT)

def clipper(clip_boundary):
	global polygon

	# Array that contains a list of the new vertices for a polygon
	tempArray = []

	for i in range(len(polygon)-1):
		v1 = polygon[i]
		v2 = polygon[i+1]

		if inside(clip_boundary, v1):
			if i == 0:
				tempArray.append(v1)

			if(inside(clip_boundary, v2)):
				tempArray.append(v2)

			else:
				v = intersection(v1, v2, clip_boundary)
				tempArray.append(v)
			
		else:
			if inside(clip_boundary, v2):
				v = intersection(v2, v1, clip_boundary)
				tempArray.append(v)
				tempArray.append(v2)

	polygon = tempArray

def inside(clip_boundary, v):

		# Really disgusting way for each case, but I couldn't think of a better way

		if (clip_boundary == TOP and v.y < world_y2):
			return True

		elif(clip_boundary == LEFT and v.x > world_x1):
			return True

		elif(clip_boundary == BOTTOM and v.y > world_y1):
			return True

		elif(clip_boundary == RIGHT and v.x < world_x2):
			return True

		return False


def intersection(v1, v2, clip_boundary):
	dx = v2.x - v1.x
	dy = v2.y - v1.y

	v = Vertex(0,0)

	# //Vertical line condition
	if(dx == 0 or dy == 0):
		if(clip_boundary == TOP):
			v.x = v1.x;
			v.y = world_y2;
		elif (clip_boundary == LEFT):
			v.x = world_x1
			v.y = v1.y
		elif (clip_boundary == BOTTOM):
			v.x = v1.x
			v.y = world_y1
		elif (clip_boundary == RIGHT):
			v.x = world_x2
			v.y = v1.y
		return v
	
	#Can't divide by 0, get slope, and find interection for each case
	slope = dy/dx;

	if(clip_boundary == LEFT):
		v.x = world_x1
		v.y = (int) (slope * (world_x1 - v1.x) + v1.y)
	
	if(clip_boundary == RIGHT):
		v.x = world_x2
		v.y = (int) (slope * (world_x2 - v1.x) + v1.y)
	if(clip_boundary == TOP):
		v.x = (int) ((world_y2 - v1.y)/slope + v1.x)
		v.y = world_y2
	
	if(clip_boundary == BOTTOM):
		v.x = (int) ((world_y1 - v1.y)/slope + v2.x)
		v.y = world_y1

	return v

# //////////////////////////////////////
# // THE DRAWING SECTION
# //////////////////////////////////////

def draw(pixels):
	# //Make everything white
	for i in range(height):
		for j in range(width):
			pixels[i][j] = '0'
	
	for i in range(len(polygon) - 1 ):

		x1 = polygon[i].x - world_x1
		y1 = polygon[i].y - world_y1
		x2 = polygon[i+1].x - world_x1
		y2 = polygon[i+1].y - world_y1

		steep = (abs(y2 - y1) > abs(x2 - x1));



		# //Slope greater than 1
		if(steep):
			(y1, x1) = (x1,y1)
			(y2, x2) = (x2,y2)

		# // Line heads left, swap points
		if(x1 > x2):
			(x1, x2) = (x2, x1)
			(y1, y2) = (y2, y1)

		dErr = abs(y2 - y1)
		yStep = -1 if y1 > y2 else 1
		dX = x2 - x1

		err = dX / 2

		y = y1

		for x in range(x1,x2):
			if steep:
				pixels[int(x)][int(y)] = '1' #drawPoint(y,x);
			else:

				pixels[int(y)][int(x)] = '1' #drawPoint(x,y);

			err -= dErr
			if(err < 0):
				y += yStep
				err += dX

def printPixels(pixels):
	print("P1");
	print("# test.pbm");
	print(width, height);

	for i in range(height-1, -1, -1):
		for j in range(width):
			print(pixels[i][j], end = " ")
		print()

# ////////////////////////////
# // TRANSFORMATIONS
# ////////////////////////////

def scalePolygon():

	for v in polygon:
		v.x = int( v.x * scaleFactor)
		v.y = int( v.y * scaleFactor)

def rotatePolygon():
	for v in polygon:
		temp_x = int( (v.x * cos(rotation) - (v.y * sin(rotation))) )
		temp_y = int( (v.x * sin(rotation) + (v.y * cos(rotation))) )
		v.x = temp_x;
		v.y = temp_y;

def translatePolygon():
	for v in polygon:
		v.x += translateX;
		v.y += translateY;

#////////////////////////
#//MAIN
#////////////////////////


if __name__ == "__main__":

	fileName = "hw2_a.ps"

	processArgs()

	width = world_x2 - world_x1 + 1
	height = world_y2 - world_y1 + 1

	pixels = []
	for i in range(height):
		col = []
		for i in range(width):
			col.append("0")
		pixels.append(col)

	readPS()

	scalePolygon()
	rotatePolygon()
	translatePolygon()

	clipping()

	draw(pixels)

	printPixels(pixels)
	
	printArray(polygon)
